name: Deploy Service

on:
  workflow_dispatch:
  push:
    paths:
      - modules/**
      - deployment/**
      - .github/workflows/deploy-service.yml

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-2

defaults:
  run:
    working-directory: ./deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/deployment-role
          role-session-name: ${{ github.event.repository.name }}
          aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-Terraform@v1
      with:
        terraform_version: 1.5.7

    - name: Setup Terragrunt
      run: |
        sudo wget -q -O /bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v0.55.2/terragrunt_linux_amd64"
        sudo chmod +x /bin/terragrunt
        terragrunt -v

      - name: Deploy
        shell: bash
        run: |
          terragrunt run-all apply -auto-approve
